class reg_dicc():
    def __init__(self):
        pass
    def get_dicc_of_regs_vista1(self, interface):
        regs = {
            "rax": interface.regRax,
            "eax": interface.regRax_2,
            "rbx": interface.regRbx,
            "ebx": interface.regRbx_2,
            "rcx": interface.regRcx,
            "ecx": interface.regRcx_2,
            "rdx": interface.regRdx,
            "edx": interface.regRdx_2,
            "rsi": interface.regRsi,
            "esi": interface.regRsi_2,
            "rdi": interface.regRdi,
            "edi": interface.regRdi_2,
            "rbp": interface.regRbp,
            "ebp": interface.regRbp_2,
            "rsp": interface.regRsp,
            "esp": interface.regRsp_2,
            "r8": interface.regR8,
            "e8": interface.regR8_2,
            "r9": interface.regR9,
            "e9": interface.regR9_2,
            "r10": interface.regR10,
            "e10": interface.regR10_2,
            "r11": interface.regR11,
            "e11": interface.regR11_2,
            "r12": interface.regR12,
            "e12": interface.regR12_2,
            "r13": interface.regR13,
            "e13": interface.regR13_2,
            "r14": interface.regR14,
            "e14": interface.regR14_2,
            "r15": interface.regR15,
            "e15": interface.regR15_2,
            "rip": interface.regRip,
            "eip": interface.regRip,
            "cs": interface.regCs,
            "ds": interface.regDs,
            "es": interface.regEs,
            "ss": interface.regSs
        }
        return regs   

    def get_dicc_of_regs_vista2(self, interface):
        regs = {
            "rax": interface.regRax_3,
            "eax": interface.regRax_4,
            "rbx": interface.regRbx_3,
            "ebx": interface.regRbx_4,
            "rcx": interface.regRcx_3,
            "ecx": interface.regRcx_4,
            "rdx": interface.regRdx_3,
            "edx": interface.regRdx_4,
            "rsi": interface.regRsi_3,
            "esi": interface.regRsi_4,
            "rdi": interface.regRdi_3,
            "edi": interface.regRdi_4,
            "rbp": interface.regRbp_3,
            "ebp": interface.regRbp_4,
            "rsp": interface.regRsp_3,
            "esp": interface.regRsp_4,
            "r8": interface.regR8_3,
            "e8": interface.regR8_4,
            "r9": interface.regR9_3,
            "e9": interface.regR9_4,
            "r10": interface.regR10_3,
            "e10": interface.regR10_4,
            "r11": interface.regR11_3,
            "e11": interface.regR11_4,
            "r12": interface.regR12_3,
            "e12": interface.regR12_4,
            "r13": interface.regR13_3,
            "e13": interface.regR13_4,
            "r14": interface.regR14_3,
            "e14": interface.regR14_4,
            "r15": interface.regR15_3,
            "e15": interface.regR15_4,
            "rip": interface.regRip_2,
            "eip": interface.regRip_2,
            "cs": interface.regCs_2,
            "ds": interface.regDs_2,
            "es": interface.regEs_2,
            "ss": interface.regSs_2
        }
        return regs  